import Head from 'next/head'
import Main from '@/components/Main'

export default function Home() {
  return (
    <>
    <Head>
        <title>दैलेखी सेवा समाज</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
        <script src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d353.51049338326686!2d85.32864997175557!3d27.7051307996466!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2snp!4v1684554198044!5m2!1sen!2snp"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
    </>
  )
}
